[package]
name = "ReinforcementLearning"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
plotters = "0.3.3"
egui = "0.31.1"
eframe = "0.31.1"
simple_chess = "1.0.2"
game_board = "1.0.1"
regex = "1.11.1"
